// const String DOMAIN = 'http://192.168.1.4:8080/api/v1/';
const String DOMAIN = 'http://192.168.1.7:8080/api/v1/';
const String LOGIN_ENDPOINT = DOMAIN + 'login';
const String COURSE_ENDPOINT = DOMAIN + 'courses';
const String NEWEST_COURSE_ENDPOINT = DOMAIN + 'courses/newest';
const String GET_ALL_COURSE_ENDPOINT = DOMAIN + 'courses';
const String SEARCH_ENDPOINT = DOMAIN +'courses/search';
const String WISHLIST = DOMAIN + "wishlist";
const String CART = DOMAIN + "cart";